USE MASTER

DROP DATABASE IF EXISTS LogInDB

GO

CREATE DATABASE LogInDB

GO

USE LogInDB

CREATE TABLE dbo.Account (
	id BINARY(16) NOT NULL PRIMARY KEY,
	email VARCHAR(320) NOT NULL UNIQUE,
	username NVARCHAR(30) NOT NULL UNIQUE,
	creationDate DATETIME NOT NULL,
	firstName NVARCHAR(64) NULL,
	lastName NVARCHAR(64) NULL
)

GO

CREATE TABLE dbo.[Password] (
	passwordId BINARY(16) NOT NULL PRIMARY KEY,
	passwordHashSalt VARCHAR(128),
	CONSTRAINT PasswordEmailFK
	FOREIGN KEY (passwordId) REFERENCES Account(id)
	ON DELETE CASCADE,
)
